name: AerialKits
api: [1.13.0]
version: "1.0_BETA"
main: AerialPHP\Main
author: Syntaxious and BoyIsDino
commands:
  akit:
   description: Shows multiple choices of kits. use /akit "kitname" to use kit.
